### ISSUE TITLE
env is not defined at the last line of eRL_demo_StockTrading.ipynb

### ISSUE THREAD

**Issue by wmmxk** [AI4Finance-Foundation/ElegantRL#35] opened 2021-07-02 01:50 UTC
I was running eRL_demo_StockTrading.ipynb. Everything is fine except at the end, it complained "env" is not defined. Do you have any ideas how to fix this?

**Comment by dwaynepaschall** [comment] 2021-07-05 21:32
I can confirm the same code error.

**Comment by dwaynepaschall** [comment] 2021-07-05 21:33
Looks like the issue may gave been resolved in this pull request: Fix graph processing issue #34

**Closed** 2022-02-08 19:06 UTC
Labels: bug
