### ISSUE TITLE
`train_and_evaluate` function only trains once

### ISSUE THREAD

**Issue by notsql** [AI4Finance-Foundation/ElegantRL#104] opened 2022-01-25 15:37 UTC
```python
import gym
from elegantrl.agent import AgentModSAC
from elegantrl.config import get_gym_env_args, Arguments
from elegantrl.run import *

gym.logger.set_level(40)  # Block warning

env_func = gym.make
env_args = {
    'env_num': 1,
    'env_name': 'LunarLanderContinuous-v2',
    'max_step': 1000,
    'state_dim': 8,
    'action_dim': 2,
    'if_discrete': False,
    'target_return': 200,
    'id': 'LunarLanderContinuous-v2'
}

train_and_evaluate(args) # Issue here
```

Although no errors was raised, the whole training only ran once instead of multiple times as showed in the examples.

**Comment by hmomin** [comment] 2022-01-25 15:39
Yes, this is something that had me concerned as well. I haven't investigated the cause yet though.

**Comment by hmomin** [comment] 2022-01-25 21:34
This should be fixed now!

**Closed by hmomin** 2022-01-25 21:34 UTC
Labels: good first issue, dicussion
